### ISSUE TITLE
Unable to get the plugin working

### ISSUE THREAD

**Issue by JDI-Developers** [DeBoerTool/html-webpack-blade-plugin#1]
Tried the following options:

```javascript
    plugins: [
      new HtmlWebpackPlugin(htmlWebpackPlugin),
      new HtmlWebpackBladePlugin()
    ]
```

htmlWebpackPlugin (logged):
```javascript
{
  template: 'webpack/template/production.html',
  minify: {
    collapseWhitespace: true, 
    preserveLineBreaks: false
  },
  chunksSortMode: 'none'
}
```

It gives the error:
`TypeError: Cannot read property 'tapAsync' of undefined`
on line `compilation.hooks.htmlWebpackPluginAfterHtmlProcessing.tapAsync(`

**Comment by danielsdeboer** [comment]
What version of Webpack are you using?

**Comment by danielsdeboer** [comment]
I've added peer deps to make clear which versions are required:

https://github.com/DeBoerTool/html-webpack-blade-plugin/blob/master/package.json

This is published under version `0.1.3` on `npm`.

**Comment by JDI-Developers** [comment]
> What version of `webpack` and `html-webpack-plugin` are you using?

Using the following versions: 
- webpack: 4.20.2
- html-webpack-plugin: 4.0.0-alpha.2

Still getting the same error: `TypeError: Cannot read property 'tapAsync' of undefined` (line 37)

**Comment by danielsdeboer** [comment]
https://github.com/jantimon/html-webpack-plugin/issues/1049#issuecomment-423142837

Check the peer deps, @next alpha releases are not supported. Try backing your `html-webpack-plugin` version down to 3.2.x
